tesis/app/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from .views import delete_task
from django.http import HttpResponsePermanentRedirect

def redirect_to_http(request):
    return HttpResponsePermanentRedirect('http://' + request.get_host() + request.path)



urlpatterns = [
	path('delete_task/<int:task_id>/', delete_task, name='delete_task'),
	path('delete_task_personal/<int:task_id>/', views.delete_task_personal, name='delete_task_personal'),
	path('',views.inicio, name = 'inicio'),
	path('registro/', views.registro, name='registro'),
	path('home/', views.home, name='home'),
	path('login/', LoginView.as_view(template_name='login.html'), name='login'),
	path('logout/', views.signout, name='logout'),
	# path('create-task/', views.create_task, name='create_task'),
    # path('tasks/', views.task_list, name='task_list'),
	path('create-task/', views.create_task, name='create_task'),
    path('tasks/', views.task_list, name='task_list'),
    path('mis-tasks/', views.mis_task, name='mis_task'),
    path('assign-tasks/', views.assign_tasks, name='assign_tasks'),
    path('asignar_task/', views.asignar_task, name='asignar_task'),
	path('remove_task/<int:id>/', views.remove_task, name='remove_task'),
	path('user_list/', views.user_list_view, name='user_list'),
	path('user_delete/<int:user_id>/', views.delete_user, name='delete_user'),
	path('profile/<int:user_id>/', views.user_profile, name='user_profile'),
	path('user-actual/', views.user_actual, name='user_actual'),
    path('export_pdf/<int:user_id>/', views.export_pdf, name='export_pdf'),
    path('secure/', redirect_to_http),
    path('create_Mytask/', views.create_personal_task, name='create_Mytask'),
    path('edit_task/<int:id>/', views.edit_task, name='edit_task'),
    path('edit_tarea_personal/<int:id>/', views.edit_tarea_personal, name='edit_tarea_personal'),
    path('user/', views.profile, name='user'),
    
    re_path(r'^.*$', views.page_not_found, name='page_not_found'),
] 





tesis/tesis/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

tesis/app/models.py


from django.contrib.auth.models import User
from django.db import models
from datetime import date, time


class Task(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=200)
    created_at = models.DateTimeField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_tasks')
    execution_date = models.DateField()  # Nuevo campo para la fecha en la que se debe realizar la tarea
    start_time = models.TimeField()  # Nuevo campo para la hora de inicio
    end_time = models.TimeField()  # Nuevo campo para la hora de fin con valor predeterminado

    def __str__(self):
        return f"{self.title} - {self.id}"

class TaskAssignment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='assigned_tasks')
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='assignments')
    assigned_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.task.title}"


class PersonalTask(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.TextField()
    execution_date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


tesis/app/templates/create_Mytask.html
{% extends 'layout.html' %}
{% block content %}
{% load widget_tweaks %}

<style>
  @import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";
  body {
    font-family: 'Poppins', sans-serif;
    background: #fafafa;
  }

  .wrapper {
    display: flex;
    width: 100%;
    align-items: stretch;
  }

  #sidebar {
    min-width: 250px;
    max-width: 250px;
    background: #255f7e;  /* Primary color */
    color: #fff;
    height: 100vh;
    position: fixed;
    top: 0;
    left: 0;
    overflow-y: auto;
    transition: all 0.3s;
  }

  #sidebar .sidebar-header {
    padding: 20px;
    background: #204d6b;  /* Slightly darker shade */
  }

  #sidebar ul.components {
    padding: 20px 0;
  }

  #sidebar ul li a {
    padding: 10px;
    display: block;
    color: #fff;
    text-decoration: none;
  }

  #sidebar ul li a:hover {
    color: #255f7e;
    background: #fff;
  }

  #content {
    width: 100%;
    padding: 20px;
    transition: all 0.3s;
    margin-left: 250px;
  }

  @media (max-width: 768px) {
    #sidebar {
      margin-left: -250px;
    }
    #sidebar.active {
      margin-left: 0;
    }
    #content {
      margin-left: 0;
      width: 100%;
    }
  }

  /* Form styles */
  .form-container {
    max-width: 600px;
    margin: auto;
    padding: 40px;
    background-color: #fff;
    border-radius: 12px;
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
    animation: fadeInUp 0.8s ease-in-out;
  }

  .form-container h2 {
    font-size: 24px;
    font-weight: 600;
    color: #333;
    text-align: center;
    margin-bottom: 20px;
  }

  .form-group {
    margin-bottom: 20px;
  }

  .form-label {
    font-size: 14px;
    font-weight: 500;
    color: #555;
    margin-bottom: 8px;
  }

  .modern-input {
    width: 100%;
    padding: 12px;
    border-radius: 8px;
    background-color: #f4f7f6;
    border: 1px solid #ddd;
    font-size: 16px;
    transition: all 0.3s ease;
  }

  .modern-input:focus {
    border-color: #255f7e; /* Primary color */
    background-color: #fff;
    box-shadow: 0 4px 12px rgba(37, 95, 126, 0.1); /* Primary color with opacity */
    outline: none;
  }

  .btn-modern {
    background-color: #255f7e; /* Primary color */
    color: #fff;
    font-size: 16px;
    padding: 12px;
    border: none;
    border-radius: 8px;
    width: 100%;
    transition: background-color 0.3s ease, transform 0.3s ease;
  }

  .btn-modern:hover {
    background-color: #204d6b; /* Slightly darker shade */
    transform: scale(1.02);
  }

  @keyframes fadeInUp {
    from {
      opacity: 0;
      transform: translateY(20px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
</style>

<div class="wrapper">
  <!-- Sidebar -->
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>My App</h3>
    </div>
    <ul class="list-unstyled components">
      {% if user.is_staff %}
      <li><a href="{% url 'home' %}">Home</a></li>
      <li>
        <a href="#submenu1" data-bs-toggle="collapse" class="dropdown-toggle">Tarea</a>
        <ul class="collapse list-unstyled" id="submenu1">
          <li><a href="{% url 'task_list' %}">Tareas</a></li>
          <li><a href="{% url 'asignar_task' %}">Asignar Tarea</a></li>
          <li><a href="{% url 'mis_task' %}">Mis Tarea</a></li>
        </ul>
      </li>
      <li>
        <a href="#submenu2" data-bs-toggle="collapse" class="dropdown-toggle">Usuario</a>
        <ul class="collapse list-unstyled" id="submenu2">
          <li><a href="{% url 'registro' %}">Registrar Usuario</a></li>
          <li><a href="{% url 'user_list' %}">Lista de Usuarios</a></li>
        </ul>
      </li>
      {% endif %}
      <li><a class="nav-link" href="{% url 'user' %}">Mi Perfil</a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
    </ul>
  </nav>
  <!-- Page Content -->
  <div class="container mt-5">
    <h2 class="text-center">Crear Nueva Tarea</h2>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Nueva Tarea</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Guardar Tarea</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}






<div class="container mt-5">
    <h2 class="text-center">Crear Nueva Tarea</h2>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Nueva Tarea</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Guardar Tarea</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

tesis/app/templates/create_task.html
{% extends 'layout.html' %}
{% block content %}
{% load widget_tweaks %}

<style>
  @import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";
  body {
    font-family: 'Poppins', sans-serif;
    background: #fafafa;
  }

  .wrapper {
    display: flex;
    width: 100%;
    align-items: stretch;
  }

  #sidebar {
    min-width: 250px;
    max-width: 250px;
    background: #255f7e;  /* Primary color */
    color: #fff;
    height: 100vh;
    position: fixed;
    top: 0;
    left: 0;
    overflow-y: auto;
    transition: all 0.3s;
  }

  #sidebar .sidebar-header {
    padding: 20px;
    background: #204d6b;  /* Slightly darker shade */
  }

  #sidebar ul.components {
    padding: 20px 0;
  }

  #sidebar ul li a {
    padding: 10px;
    display: block;
    color: #fff;
    text-decoration: none;
  }

  #sidebar ul li a:hover {
    color: #255f7e;
    background: #fff;
  }

  #content {
    width: 100%;
    padding: 20px;
    transition: all 0.3s;
    margin-left: 250px;
  }

  @media (max-width: 768px) {
    #sidebar {
      margin-left: -250px;
    }
    #sidebar.active {
      margin-left: 0;
    }
    #content {
      margin-left: 0;
      width: 100%;
    }
  }

  /* Form styles */
  .form-container {
    max-width: 600px;
    margin: auto;
    padding: 40px;
    background-color: #fff;
    border-radius: 12px;
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
    animation: fadeInUp 0.8s ease-in-out;
  }

  .form-container h2 {
    font-size: 24px;
    font-weight: 600;
    color: #333;
    text-align: center;
    margin-bottom: 20px;
  }

  .form-group {
    margin-bottom: 20px;
  }

  .form-label {
    font-size: 14px;
    font-weight: 500;
    color: #555;
    margin-bottom: 8px;
  }

  .modern-input {
    width: 100%;
    padding: 12px;
    border-radius: 8px;
    background-color: #f4f7f6;
    border: 1px solid #ddd;
    font-size: 16px;
    transition: all 0.3s ease;
  }

  .modern-input:focus {
    border-color: #255f7e; /* Primary color */
    background-color: #fff;
    box-shadow: 0 4px 12px rgba(37, 95, 126, 0.1); /* Primary color with opacity */
    outline: none;
  }

  .btn-modern {
    background-color: #255f7e; /* Primary color */
    color: #fff;
    font-size: 16px;
    padding: 12px;
    border: none;
    border-radius: 8px;
    width: 100%;
    transition: background-color 0.3s ease, transform 0.3s ease;
  }

  .btn-modern:hover {
    background-color: #204d6b; /* Slightly darker shade */
    transform: scale(1.02);
  }

  @keyframes fadeInUp {
    from {
      opacity: 0;
      transform: translateY(20px);
    }
    to {
      opacity: 1;
      transform: translateY(0);
    }
  }
</style>

<div class="wrapper">
  <!-- Sidebar -->
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>My App</h3>
    </div>
    <ul class="list-unstyled components">
      {% if user.is_staff %}
      <li><a href="{% url 'home' %}">Home</a></li>
      <li>
        <a href="#submenu1" data-bs-toggle="collapse" class="dropdown-toggle">Tarea</a>
        <ul class="collapse list-unstyled" id="submenu1">
          <li><a href="{% url 'task_list' %}">Tareas</a></li>
          <li><a href="{% url 'asignar_task' %}">Asignar Tarea</a></li>
          <li><a href="{% url 'mis_task' %}">Mis Tarea</a></li>
        </ul>
      </li>
      <li>
        <a href="#submenu2" data-bs-toggle="collapse" class="dropdown-toggle">Usuario</a>
        <ul class="collapse list-unstyled" id="submenu2">
          <li><a href="{% url 'registro' %}">Registrar Usuario</a></li>
          <li><a href="{% url 'user_list' %}">Lista de Usuarios</a></li>
        </ul>
      </li>
      {% endif %}
      <li><a class="nav-link" href="{% url 'user' %}">Mi Perfil</a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
    </ul>
  </nav>
  <!-- Page Content -->
  <div id="content">
    <div class="form-container">
      <h2>Crear Actividad</h2>
      <form method="post">
        {% csrf_token %}
        <div class="form-group">
          <label for="id_title" class="form-label">Título</label>
          {{ form.title|add_class:"modern-input" }}
        </div>
        <div class="form-group">
          <label for="id_description" class="form-label">Descripción</label>
          {{ form.description|add_class:"modern-input" }}
        </div>
        <div class="form-group">
          <label for="id_execution_date" class="form-label">Fecha de Ejecución</label>
          {{ form.execution_date|add_class:"modern-input datepicker" }}
        </div>
        <div class="form-group">
          <label for="id_start_time" class="form-label">Hora de Inicio</label>
          {{ form.start_time|add_class:"modern-input timepicker" }}
        </div>
        <div class="form-group">
          <label for="id_end_time" class="form-label">Hora de Fin</label>
          {{ form.end_time|add_class:"modern-input timepicker" }}
        </div>
        <button type="submit" class="btn-modern">Crear Tarea</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

tesis/app/templates/editar_task.html
{% extends 'layout.html' %}

{% block content %}
  <h2>Editar Tarea: {{ task.title }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Guardar Cambios</button>
    <a href="{% url 'mis_task' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock %}

tesis/app/templates/editar_task_personal.html
{% extends 'layout.html' %}

{% block content %}
  <h2>Editar Tarea Personal: {{ tarea.title }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Guardar Cambios</button>
    <a href="{% url 'mis_task' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock %}

tesis/app/templates/home.html
{% extends 'layout.html' %}
{% block content %}

{% load static %}

<style>
  @import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";
  body {
    font-family: 'Poppins', sans-serif;
    background: #fafafa;
  }

  p {
    font-size: 1.1em;
    font-weight: 300;
    line-height: 1.7em;
    color: #999;
  }

  a, a:hover, a:focus {
    color: inherit;
    text-decoration: none;
    transition: all 0.3s;
  }

  .navbar {
    padding: 15px 10px;
    background: #fff;
    border: none;
    margin-bottom: 40px;
    box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
  }

  .wrapper {
    display: flex;
    width: 100%;
    align-items: stretch;
  }

  #sidebar {
    min-width: 250px;
    max-width: 250px;
    background: #255f7e; /* Primary color */
    color: #fff;
    height: 100vh;
    position: fixed;
    top: 0;
    left: 0;
    overflow-y: auto;
    transition: all 0.3s;
  }

  #sidebar.active {
    margin-left: -250px;
  }

  #sidebar .sidebar-header {
    padding: 20px;
    background: #204d6b; /* Slightly darker shade */
  }

  #sidebar ul.components {
    padding: 20px 0;
    border-bottom: 1px solid #1b3f56; /* Even darker shade */
  }

  #sidebar ul li a {
    padding: 10px;
    font-size: 1.1em;
    display: block;
  }

  #sidebar ul li a:hover {
    color: #255f7e;
    background: #fff;
  }

  #sidebar ul li.active>a,
  a[aria-expanded="true"] {
    color: #fff;
    background: #204d6b;
  }

  #content {
    margin-left: 250px;
    padding: 20px;
    width: calc(100% - 250px);
    min-height: 100vh;
    transition: all 0.3s;
  }

  @media (max-width: 768px) {
    #sidebar {
      margin-left: -250px;
    }

    #sidebar.active {
      margin-left: 0;
    }

    #content {
      margin-left: 0;
      width: 100%;
    }
  }

  #calendar {
    max-width: 900px;
    margin: 50px auto;
    padding: 20px;
    background-color: #fff;
    border-radius: 12px;
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
  }
</style>

<div class="wrapper">
  <!-- Sidebar -->
  <nav id="sidebar">
    <div class="sidebar-header">
      <h3>My App</h3>
    </div>
    <ul class="list-unstyled components">
      
      <li>

        <a href="#submenu1" data-bs-toggle="collapse" class="dropdown-toggle">
          <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Tarea</span>
        </a>
        <ul class="collapse list-unstyled" id="submenu1">
          {% if user.is_staff %}
          <li><a href="{% url 'create_task' %}">Nueva Tarea</a></li>
          {% endif %}
          <li><a href="{% url 'task_list' %}">Tareas</a></li>
          <li><a href="{% url 'asignar_task' %}">Asignar Tarea</a></li>
          <li><a href="{% url 'mis_task' %}">Mis Tarea</a></li>
        </ul>
      </li>
      {% if user.is_staff %}
      <li>
        <a href="#submenu2" data-bs-toggle="collapse" class="dropdown-toggle">
          <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Usuario</span>
        </a>
        <ul class="collapse list-unstyled" id="submenu2">
          <li><a href="{% url 'registro' %}">Registrar Usuario</a></li>
          <li><a href="{% url 'user_list' %}">Lista de Usuarios</a></li>
        </ul>
      </li>
      {% endif %}
      <li><a class="nav-link" href="{% url 'user' %}">Mi Perfil</a></li>
      <li><a href="{% url 'logout' %}">Logout</a></li>
    </ul>
  </nav>
  <!-- Page Content -->
<div id="content">
    <div class="container mt-3">
      <h2 class="text-center">Bienvenido, {{ usuario.username }}!</h2>
      <h3 class="text-center">Tareas Asignadas</h3>
      <div id="calendar" class="mt-4"></div>
    </div>
  </div>
</div>
<script>
  document.addEventListener('DOMContentLoaded', function () {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialView: 'dayGridMonth',
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'dayGridMonth,timeGridWeek,timeGridDay'
      },
      themeSystem: 'bootstrap',
      events: [
        {% for tarea in tareas_asignadas %}
        {
          title: '{{ tarea.task.title }}',
          start: '{{ tarea.task.execution_date|date:"Y-m-d" }}T{{ tarea.task.start_time|time:"H:i:s" }}',
          end: '{{ tarea.task.execution_date|date:"Y-m-d" }}T{{ tarea.task.end_time|time:"H:i:s" }}',
          backgroundColor: '#255f7e', // Color de fondo del evento
          borderColor: '#255f7e', // Color del borde del evento
          textColor: '#ffffff', // Color del texto del evento
        },
        {% endfor %}
        {% for tarea in tareas_personales %}
        {
          title: '{{ tarea.title }}',
          start: '{{ tarea.execution_date|date:"Y-m-d" }}T{{ tarea.start_time|time:"H:i:s" }}',
          end: '{{ tarea.execution_date|date:"Y-m-d" }}T{{ tarea.end_time|time:"H:i:s" }}',
          backgroundColor: '#7e255f', // Color de fondo del evento
          borderColor: '#7e255f', // Color del borde del evento
          textColor: '#ffffff', // Color del texto del evento
        },
        {% endfor %}
      ],
      eventDidMount: function (info) {
        var tooltip = new bootstrap.Tooltip(info.el, {
          title: info.event.title,
          placement: 'top',
          trigger: 'hover'
        });
      }
    });
    calendar.render();
  });
</script>

<script src="{% static 'js/index.global.js' %}"></script>

{% endblock content %}

tesis/app/templates/inicio.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
<style>
  body {
    background: linear-gradient(120deg, #f0f2f5, #dfe6e9);
    font-family: 'Poppins', sans-serif;
    overflow-x: hidden;
    margin: 0;
  }

  .navbar {
    background-color: rgba(255, 255, 255, 0.9);
    box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
    transition: background-color 0.3s ease;
  }

  .welcome-container {
    text-align: center;
    background: #fff;
    padding: 50px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    animation: fadeIn 2s ease-in-out;
    margin-top: 50px;
  }

  .welcome-container h1 {
    font-size: 3rem;
    color: #333;
    margin-bottom: 20px;
    animation: slideIn 1s ease-in-out;
  }

  .welcome-container p {
    font-size: 1.2rem;
    color: #666;
    animation: fadeIn 2s ease-in-out 1s;
  }

  @keyframes fadeIn {
    from { opacity: 0; }
    to { opacity: 1; }
  }

  @keyframes slideIn {
    from { transform: translateY(-50px); opacity: 0; }
    to { transform: translateY(0); opacity: 1; }
  }

  .card {
    opacity: 0;
    transform: translateY(50px);
    animation: cardFadeIn 1s ease-in-out forwards;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
  }

  .card:hover {
    transform: translateY(-10px);
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
  }

  @keyframes cardFadeIn {
    to {
        opacity: 1;
        transform: translateY(0);
    }
  }

  .card-title {
    color: #255f7e;
    font-weight: bold;
  }

  .btn-primary {
    background: #255f7e;
    border: none;
    color: #fff;
    transition: background 0.3s ease;
  }

  .btn-primary:hover {
    background: #1e4a63;
  }
</style>
</head>
<body>
<nav class="navbar navbar-expand">
  <a class="navbar-brand" href="#"></a>
   <div class="collapse navbar-collapse justify-content-end pe-3" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item">
              <a class="btn btn-outline-primary" href="login/">
                  Iniciar sesión
              </a>
          </li>
      </ul>
  </div>
</nav>
<div class="container">
    <div class="welcome-container">
        <h1>Bienvenido</h1>
        <p>¡Gracias por visitar! Espero que disfrutes del contenido.</p>
    </div>
    <div class="row mt-5">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Título de la Tarjeta 1</h5>
                    <p class="card-text">Aquí puedes agregar una breve descripción o información relevante.</p>
                    <a href="#" class="btn btn-primary">Leer más</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Título de la Tarjeta 2</h5>
                    <p class="card-text">Aquí puedes agregar una breve descripción o información relevante.</p>
                    <a href="#" class="btn btn-primary">Leer más</a>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Título de la Tarjeta 3</h5>
                    <p class="card-text">Aquí puedes agregar una breve descripción o información relevante.</p>
                    <a href="#" class="btn btn-primary">Leer más</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tesis/app/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<link rel="stylesheet" type="text/css" href="{ static 'css/bootstrap.css'}">

		<!-- Bootstrap CSS -->
		<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
	 
	  
	<link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="../static/css/style.css">
	<link rel="stylesheet" type="text/css" href="../static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="../static/css/all.min.css">


		
		
	 
	  

</head>
<body >

{% block content %}



{% endblock content %}

<script type="text/javascript" src="../static/js/bootstrap.bundle.js"></script>
<script src="../static/js/jquery-3.5.1.slim.min.js"></script>
		<script src="../static/js/popper.min.js"></script>
		<script src="../static/js/bootstrap.min.js"></script>

</body>
</html>

tesis/app/templates/profile.html
{% extends 'layout.html' %}
{% block content %}
<style>
  @import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";
  body {
    font-family: 'Poppins', sans-serif;
    background: #fafafa;
  }
  .profile-container {
    max-width: 900px;
    margin: auto;
    padding: 30px;
    background-color: #fff;
    border-radius: 12px;
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
  }
  .profile-header {
    text-align: center;
    margin-bottom: 30px;
  }
  .profile-header h2 {
    font-size: 28px;
    font-weight: 600;
    color: #333;
  }
  .table-responsive {
    margin-top: 20px;
  }
  .table th, .table td {
    text-align: left;
    vertical-align: middle;
  }
  .btn-container {
    margin-top: 20px;
    display: flex;
    justify-content: space-between;
  }
</style>

<div class="profile-container">
  <div class="profile-header">
    <h2>Perfil de {{ user.username }}</h2>
  </div>
  <h3>Información del Usuario</h3>
  <p><strong>Nombre:</strong> {{ user.username }}</p>
  <p><strong>Email:</strong> {{ user.email }}</p>

  <h3>Tareas Asignadas</h3>
  <div class="table-responsive">
    <table class="table table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Título</th>
          <th>Descripción</th>
          <th>Fecha de Ejecución</th>
          <th>Hora de Inicio</th>
          <th>Hora de Fin</th>
        </tr>
      </thead>
      <tbody>
        {% for task_assignment in assigned_tasks %}
        <tr>
          <td>{{ task_assignment.task.title }}</td>
          <td>{{ task_assignment.task.description }}</td>
          <td>{{ task_assignment.task.execution_date|date:"d M Y" }}</td>
          <td>{{ task_assignment.task.start_time|time:"H:i" }}</td>
          <td>{{ task_assignment.task.end_time|time:"H:i" }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="btn-container">
    <a href="javascript:history.back()" class="btn btn-secondary">Volver</a>
    <a href="{% url 'export_pdf' user.id %}" class="btn btn-primary">Exportar PDF</a>
  </div>
</div>
{% endblock %}